<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="/pasimo/index.jsp"/>
<noscript>
	<meta http-equiv="refresh" content="5;/pasimo/index.jsp">
</noscript>
<!--[if lt IE 9]-->
<script type="text/javascript">var IE_fix=true;</script>
<!-- [endif]-->
<script type="text/javascript">
	var url = "/hospital/";
	var delay = "5000";
	window.onload = function ()
	{
		setTimeout(GoToURL, delay);
	}
	function GoToURL()
	{
		if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
		{
			var referLink = document.createElement("a");
			referLink.href = url;
			document.body.appendChild(referLink);
			referLink.click();
		}
		else { window.location.replace(url); } // All other browsers
	}
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
	href="<s:url value="/common/css/bootstrap.min.css"/>" />

<!-- Website CSS style -->
<link rel="stylesheet" href="<s:url value="/common/css/main.css"/>" />

<!-- Website Font style -->
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Passion+One'
	rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Oxygen'
	rel='stylesheet' type='text/css'>
<link rel="stylesheet"
	href="<s:url value="/common/plugins/AdminLTE/css/AdminLTE.min.css"/>" />
<%-- <link rel="stylesheet" href="<s:url value='/common/css/login_style.css'/>" /> --%>

<title>Pasimo | logging out</title>
</head>
<body class="bg-delphini">
	<div class="container">
		<div class="row main">
			<div class="panel-heading">
				<div class="login-logo">
					<span class="logo-lg"><img
						style="height: 50px;"
						src="<c:url value='/images/download.png'></c:url>" />Pas<b>Imo</b><img
						style="height: 50px;"
						src="<c:url value='/images/download.png'></c:url>" /></span>
				</div>
			</div>
			<div class="main-login main-center">

				<p>
					You will be redirected in: <small id="counter">5</small> seconds...
				</p>

			</div>
		</div>
	</div>

	<script type="text/javascript" src="common/js/bootstrap.js"></script>
		

	<script>
		setInterval(function() {
			var small = document.querySelector("#counter");
			var count = small.textContent * 1 - 1;
			small.textContent = count;
		}, 1000);
	</script>
</body>
</html>